### ISSUE TITLE
UndefRefError when trying to sample from a cube

### ISSUE THREAD

**Issue by felixcremer** [JuliaDataCubes/YAXArrays.jl#115]
When I try to sample from a cube using the following code I get an `UndefRefError`.
I can circumvent the error by adding a @show call into the inner loop, but this will bloat the runtime and also the output. 
Just doing the isassigned check in the inner loop without printing only helped sometimes. Just doing an `@show`did help.
```julia
using YAXArrays, Zarr
function outerapplymask(cube, mask; artype=YAXArray)

    maskaxs = caxes(mask)
    applyaxs = setdiff(caxes(cube), caxes(mask))
    indims = InDims(applyaxs..., artype=artype)
    #inmask = InDims(MovingWindow.(maskaxs, 0,0)..., window_oob_value=0)
    outdims=OutDims()
    outvec = []
    mapCube(innerapplymask, (cube, mask), outvec; indims=(indims, InDims()), outdims);
    for i in eachindex(outvec)
        if !isassigned(outvec,i)
            @show i
        end
        end
    sampleax = CategoricalAxis("Sample", ["Sample_$i" for i in 1:length(outvec)])
    outcube = concatenatecubes(outvec, sampleax)
    return outcube

end

function innerapplymask(xout, xin, xmask, outvec)
    if only(xmask) == 1
        selcube = deepcopy(xin)
        # Uncommenting this line removes the error
       #@show isassigned(xin.data,1)
        selcube[1,1]
        push!(outvec, selcube)
        return nothing
    else
        return nothing
    end
end

cube = Cube("undefrefcubelarge.zarr/")
mask = Cube("undefrefmask.zarr/")

sample = outerapplymask(cube, mask; artype=YAXArray)
```
This leads to the following error:
```julia
julia> sample = outerapplymask(cube, mask; artype=YAXArray)
i = 2353
i = 2865
ERROR: UndefRefError: access to undefined reference
Stacktrace:
 [1] getindex
   @ ./array.jl:861 [inlined]
 [2] concatenatecubes(cl::Vector{Any}, cataxis::CategoricalAxis{String, :Sample, Vector{String}})
   @ YAXArrays.Cubes ~/.julia/packages/YAXArrays/hcn1C/src/Cubes/TransformedCubes.jl:33
 [3] outerapplymask(cube::YAXArray{Union{Missing, Float32}, 4, ZArray{Union{Missing, Float32}, 4, Zarr.BloscCompressor, DirectoryStore}, Vector{CubeAxis}}, mask::YAXArray{Union{Missing, Int8}, 2, ZArray{Union{Missing, Int8}, 2, Zarr.BloscCompressor, DirectoryStore}, Vector{RangeAxis{Float64, S, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}} where S}}; artype::Type)
   @ Main ~/Daten/esdltests/undefreferror.jl:17
 [4] top-level scope
   @ REPL[11]:1
```

The two cubes and the script  is available here:
https://nextcloud.bgc-jena.mpg.de/s/zJmxck5ZssTxK88

This is on YAXArrays 0.2.0.

**Comment by meggart** [comment]
Ah now I understand what you are trying to do. This will not work when threading is enabled, since it will lead to race conditions when pushing into `outvec`. So make sure to do this kind of stuff only when threading is enabled. I really have to find the time and make a DiskArrays-based solution for this...

**Comment by meggart** [comment]
Can you try if the problem persists with JULIA_NUM_THREADS=1?

**Comment by felixcremer** [comment]
The problem is solved, when I use only one thread.
Is there a way to only use one thread for specific mapCube calls?
Because I would like to have the masking single threaded, and then I would like to be able to do multithreaded computations on the result of the masking.

**Comment by meggart** [comment]
Yes, there is a currently undocumented keyword argument to `mapCube`, you can set `nthreads=[1]` and it should use only one thread.
