### ISSUE TITLE
Allow getindex for Axis

### ISSUE THREAD

**Issue by meggart** [JuliaDataCubes/YAXArrays.jl#128]
We should implement getindex on CubeAxis objects, so that we could do `axis[a]` instead of `axis.values[a]`

**Comment by Sonicious** [comment]
As we discussed, this could be done while as well bring iteration along axes into the module.

**Comment by Sonicious** [comment]
Working on it outside the module-movement, because the submodule/module change might be more complex than expected.

Difficulty so far: With AbstractArray implementation, this breakes:
```
newcube = concatenatecubes(singlecubes, CategoricalAxis("ZVals", ["A", "B", "C"]))
@test caxes(newcube) == [axlist; CategoricalAxis("ZVals", ["A", "B", "C"])]
```

So the question is, how far this is used at all? Or which method is there to overload to prevent the change.
