### ISSUE TITLE
Index wishlist

### ISSUE THREAD

**Issue by jcortesr** [JuliaDataCubes/YAXArrays.jl#171]
Hi, 

on Felix's request, here is a wish list for indexing cubes:

- For the time axis, can we remove a Date(s) by using -(Date(s))
- Alternatively can we give it a vector of dates that we wish to keep? Specifying a range does not work as my purpose is to remove February 29...
- Access the axes by index rather than the value itself, e.g., my_cube[time = 1] would give the first time step
- ...

Cheers, 
Jose

**Comment by lazarusA** [comment]
see https://juliadatacubes.github.io/YAXArrays.jl/dev/UserGuide/select.html
