### ISSUE TITLE
Bump compat for "Interpolations" to "0.14"?

### ISSUE THREAD

**Issue by BernhardAhrens** [JuliaDataCubes/YAXArrays.jl#174]
YAXArrays.jl has a compat requirement for of `Interpolations = "0.12, 0.13"`. Would it be possible to bump that to 0.14?

**Comment by meggart** [comment]
Yes, definitely. I just realized that CompatHelper has been erroring for quite some time and updated the Github Action script. Let's see which other dependencies are outdated...

**Comment by felixcremer** [comment]
I just updated all compat entries and registered a new minor version. This should be available in 15 minutes.
