### ISSUE TITLE
missing documentation for exporting a cube as netcdf

### ISSUE THREAD

**Issue by jcortesr** [JuliaDataCubes/YAXArrays.jl#180]
When saving a cube to netcdf, the function `savecube` is documented to only accept arguments `(cube,name::String)`.  Simply doing `savecube(my_cube, "/my/file/path.nc")` does NOT work for me. Before (when it was called `exportcube`) it seems that simply writing the filename ending in `.nc` worked.

I had to do `savecube(my_cube, "/my/file/path.nc", backend = :netcdf, max_cache = 10e9, overwrite = true)`. Note that the default for max_cache is `1e8` and not `10e8` as in many(?) other YAXarray functions...

I leave this here in case anyone else is having problems saving as netcdf.

**Comment by felixcremer** [comment]
When you want to save a cube as a NetCDF you would need to expose the netcdf backend by loading the NetCDF package via `using NetCDF`. It seems as if you have done that in between your two function calls.

**Comment by dpabon** [comment]
This is already in the documentation. I think you can close this one. ;)
