### ISSUE TITLE
Axis manipulation

### ISSUE THREAD

**Issue by dpabon** [JuliaDataCubes/YAXArrays.jl#187]
I have two cubes with different longitude range axis. In the first cube the axis ```lon``` is ```Axis with 360 Elements from -180.0 to 179.0```. In the second cube "lon" is ```from 0.0 to 358.75```

is there an easy way to manipulate the axis to get both cubes on the same longitude range? Something like:
```
lon = getAxis("lon", cube_1).values
new_lon = mod.(lon, 360) .- 180
setaxis!(cube_1, :lon, new_lon)
```

**Comment by felixcremer** [comment]
You can use `renameaxis!` for that.
I assume, that you have the same number of elements and this is just a shift of the axis.

```julia
lon = getAxis("lon", cube_1)
renameaxis!(cube2, "lon"=>lon
```
This will replace the lon axis of the second cube by the lon axis of the first cube. 

This should be added to the documentation as a short howto.

**Comment by lazarusA** [comment]
but then, you don't need also to shift the data in your cube2? really?

**Comment by dpabon** [comment]
I did a small test... and yes, you need to shift the data manually.
```julia
altitude = Cube(altitude)
lon = getAxis("lon", altitude)
lon.values
0.0:1.25:358.75
Plots.heatmap(altitude.data)
```
![original_lon](https://user-images.githubusercontent.com/13040959/204276584-00e2bffb-434a-4cdf-a49b-3dea950d02e1.svg)

```julia
lon_new = RangeAxis("lon", range(-180, 180, length = length(lon.values)))
renameaxis!(altitude, "lon" => lon_new)
Plots.heatmap(altitude.data)
```
![original_lon](https://user-images.githubusercontent.com/13040959/204276584-00e2bffb-434a-4cdf-a49b-3dea950d02e1.svg)

Curiously, the original axis range is not replaced on the heatmap, although the cube reported the new range axis

```julia
YAXArray with the following dimensions
lon                 Axis with 288 Elements from -180.0 to 180.0
lat                 Axis with 192 Elements from -90.0 to 90.0
name: orog
units: m
Total size: 216.0 KB
```
