### ISSUE TITLE
How to contribute to the documentation?

### ISSUE THREAD

**Issue by dpabon** [JuliaDataCubes/YAXArrays.jl#188]
I would like to contribute to the documentation, but I'm not sure where to start. I wondered if there is a task list. So far, my idea is that the example presented on the README file is a bit abstract for newcomers. I was thinking on a more compelling example: 

1. Loading a Netcdf file maybe from: https://www.unidata.ucar.edu/software/netcdf/examples/files.html
2. Do some operations with mapcube.
3. Plotting with GeoMakie
4. Writing the results into a file.
5. Loading a Zarr and netcdf file from different files but the same spatial distribution.
6. Using mapcube to do operations on both cubes/files

**Comment by lazarusA** [comment]
I will try to revamp a PR with a new docs structure during the weekend. For sure I will include your suggestions and I will add some TODOs for contributions.

**Comment by dpabon** [comment]
Great, thanks! I was also thinking of including a common questions and answers section, something like:

# Common questions and answers
**Question**: What files does XAYArrays support?
**Answer**: Currently XAYArrays supports NetCDF, Zarr, ... 

**Q**: The size of my files is 300 GB and I don't have a supercomputer to run the analysis, is XAYArrays useful in this case?
**A**: Yes, no matter if your computer has 8 GB or 200 GB of RAM, every XAYArrays cube is a "lazy" representation of the real dataset. Moreover, XAYArrays takes care of the operations you want to perform efficiently without the need to write loops using MapCube. So, you don't have to worry about your computer's RAM.

**Q**: I want to run my code in parallel, but I don't want to rewrite it, can I do something without much effort?
**A**: Sure! just call Julia with multiple threads:
```sh
julia --threads 4
```
and run your code as usual, Julia and YAXArrays take care of the rest ;)
If you are working in VScode simply go to ...
![image](https://user-images.githubusercontent.com/13040959/197161166-2e0dde0b-fe09-43df-9ee8-01c59f8baedc.png)
and change the value.

**Q**: I have a problem with XAYArrays, where can I find help?
**A**: XAYArrays is in active development, then bugs can happen time to time. Please first check the documentation XXXXX, in case you don't find an answer, check the [issues web-page](https://github.com/JuliaDataCubes/YAXArrays.jl/issues) and post your issue or question. Before posting, please check that your question has not been asked and answered before. 

**Q**: How can I cite XAYArrays?
**A**: Citation XXXX + BibTex

**Q**: XAYArrays is very efficient. But, what about plotting my results?
**A**: We got you! Have a look at [GeoMakie](https://geo.makie.org/stable/), you can also check [Beautiful Makie](https://beautiful.makie.org/dev/examples/generated/2d/geo/coastlines/) for examples or inspiration.

**Comment by dpabon** [comment]
Cool! Amazing job! I'll have a look at the end of this week.

**Comment by lazarusA** [comment]
@meggart How can I (we) cite XAYArrays?

**Comment by lazarusA** [comment]
@dpabon  I added a new section `How do I ...` [here](https://juliadatacubes.github.io/YAXArrays.jl/dev/examples/generated/HowdoI/extract_axes_names/) to answer short practical issues/questions. Please suggest more.

**Comment by meggart** [comment]
> @meggart How can I (we) cite XAYArrays?

Good question. I just enabled the Zenodo hook for both YAXArrays and EarthDataLab. This means that from the next release on we will get a DOI autonatically for every release we do.
