### ISSUE TITLE
Access to attributes?

### ISSUE THREAD

**Issue by Balinus** [JuliaDataCubes/YAXArrays.jl#191]
Hello!

I'm currently exploring the YAXArrays.jl library with great success so far. However, I was wondering how the attributes of NetCDF and Zarr files are handled? So far, when I read Zarr files, I get the data, but not the metadata associated with the file. 

Here's a MWE comparing YAXArrays and xarray for a public https Zarr file, hoping it could helps. In this case, the Attributes metadata are simple, but we often have some files with lots of metadata and it is often useful to have access to it within the object/structure. 

```julia
using Zarr, YAXArrays
store_era5 = "https://s3.us-east-1.wasabisys.com/era5/world/reanalysis/single-levels/zarr/timeseries/archive"
g = zopen(store_era5, consolidated=true)
ds = open_dataset(g)
c = Cube(ds)

YAXArray with the following dimensions
longitude           Axis with 1440 Elements from -180.0 to 179.75
latitude            Axis with 721 Elements from 90.0 to -90.0
time                Axis with 368184 Elements from 1979-01-01T00:00:00 to 2020-12-31T23:00:00
Variable            Axis with 2 elements: tp t2m 
units: K
Total size: 2.78 TB
```

```python
import xarray as xr
import requests
import aiohttp

store_era5 = "https://s3.us-east-1.wasabisys.com/era5/world/reanalysis/single-levels/zarr/timeseries/archive"
ds = xr.open_zarr(store_era5)
ds

<xarray.Dataset>
Dimensions:    (latitude: 721, longitude: 1440, time: 368184)
Coordinates:
  * latitude   (latitude) float32 90.0 89.75 89.5 89.25 ... -89.5 -89.75 -90.0
  * longitude  (longitude) float32 -180.0 -179.8 -179.5 ... 179.2 179.5 179.8
  * time       (time) datetime64[ns] 1979-01-01 ... 2020-12-31T23:00:00
Data variables:
    t2m        (time, latitude, longitude) float32 dask.array<chunksize=(14880, 15, 15), meta=np.ndarray>
    tp         (time, latitude, longitude) float32 dask.array<chunksize=(14880, 15, 15), meta=np.ndarray>
Attributes:
    institution:  ECMWF
    source:       Reanalysis
    title:        ERA5 forecasts

```

**Comment by Balinus** [comment]
Humm, I played a little bit more with the YAXArrays library and found out that the `open_dataset` was returning a Dataset with the metatada. I guess my question now is what is the difference between the `Dataset` and `Cube` type?

```julia
YAXArray Dataset
Dimensions: 
   longitude           Axis with 1440 Elements from -180.0 to 179.75
   latitude            Axis with 721 Elements from 90.0 to -90.0
   time                Axis with 368184 Elements from 1979-01-01T00:00:00 to 2020-12-31T23:00:00
Variables: tp t2m 
Properties: source => Reanalysis title => ERA5 forecasts institution => ECMWF
```

**Comment by lazarusA** [comment]
I use Dataset when some dimensions for some variables are different. In that case you cannot cubed the whole object, you can only cube variables that share the same dimensions. Maybe the docs could clarify further: https://juliadatacubes.github.io/YAXArrays.jl/dev/examples/generated/UserGuide/creating/#properties-attributes

**Comment by Balinus** [comment]
> I use Dataset when some dimensions for some variables are different. In that case you cannot cubed the whole object, you can only cube variables that share the same dimensions. Maybe the docs could clarify further: https://juliadatacubes.github.io/YAXArrays.jl/dev/examples/generated/UserGuide/creating/#properties-attributes

Oh, thanks!

So, cube are when all variables have the same dimensions and Dataset is there to hold different cubes that does not share same dimensions. It is a little bit cumbersome I guess. Would it be cleaner to have something like:

Cube -> 1 variable
Dataset -> multiple Cube that can share (or not) dimensions

?

**Comment by lazarusA** [comment]
I do Datasets, 😄 . But for operations across same dimensions a Cube and using mapCube, or mapslices is quite useful when [applying functions](https://juliadatacubes.github.io/YAXArrays.jl/dev/examples/generated/UserGuide/applyfunctions/#apply-a-function-on-every-element-of-a-datacube)

**Comment by Balinus** [comment]
> I do Datasets, 😄 . But for operations across same dimensions a Cube and using mapCube, or mapslices is quite useful when [applying functions](https://juliadatacubes.github.io/YAXArrays.jl/dev/examples/generated/UserGuide/applyfunctions/#apply-a-function-on-every-element-of-a-datacube)

Thanks!
