### ISSUE TITLE
logo

### ISSUE THREAD

**Issue by lazarusA** [JuliaDataCubes/YAXArrays.jl#245]
We are missing a proper logo for this package. Any ideas, suggestions in this regard will be highly appreciated. 

Maybe @pdimens would have nice suggestions. His recent work on Tidier.jl was amazing.

**Comment by pdimens** [comment]
Ah, thanks! Would you mind giving me a brief explanation of this package?

**Comment by lazarusA** [comment]
Yet another xarray-like (YAXArrays) Julia package.

A package for operating on out-of-core labeled arrays, based on stores like NetCDF, Zarr or GDAL. Similar to [xarray](https://docs.xarray.dev/en/stable/index.html) but in Julia.

**Comment by pdimens** [comment]
Are there any themes or ideas you might be interested in incorporating?

**Comment by lazarusA** [comment]
maybe something like the following, but better 😄 , better colours, name, etc. But yeah, something along those lines.

![logo](https://user-images.githubusercontent.com/19525261/226132796-30688239-9878-41d8-833e-7f0b3fb4a0a7.png)

**Comment by pdimens** [comment]
Ok, I'll think on it. My initial idea was to be a bit playful and use a Jenga theme. Something like ![this](https://as1.ftcdn.net/v2/jpg/03/34/10/34/1000_F_334103494_2zWmU4iRsfJIbh2Qf1Uwij76zCNmeQIW.jpg)

**Comment by lazarusA** [comment]
Ohh, that's a good idea. As long as there is a 3d perspective element. Hence the cube of cubes above. In reality, yes our data structures do look like a Jena.

**Comment by pdimens** [comment]
Here's some initial drafts. I welcome your suggestions :smile: 
![image](https://user-images.githubusercontent.com/19176506/226440178-b50fc980-17e9-4f96-8f52-e90754271e1f.png)

**Comment by pdimens** [comment]
Another idea
![image](https://user-images.githubusercontent.com/19176506/226441472-4e70bb16-699f-42ab-a40a-29cc91bdbd42.png)

**Comment by lazarusA** [comment]
thanks so much for taking the time and effort, I do like the last one. And if were just me I will go for that one 😄 , but, @felixcremer and @meggart what do you guys think?

**Comment by pdimens** [comment]
I went with Julia colors (obvs) but it can be whatever you like.

**Comment by MartinuzziFrancesco** [comment]
those are very nice designs, thanks for taking the time! my two cents are that I'd keep the name and logo separated (like in the first logo) so the image can be shrunk and it still remains clear

**Comment by gdkrmr** [comment]
I have an idea, in case you like hexagonal logos: if you view a cube just from the right angle, it looks like a hexagon. At least in parallel perspective.

**Comment by pdimens** [comment]
R runs a monopoly on hexagon logos.

**Comment by pdimens** [comment]
Is there a preference for typeface of the package name? I went with a sans serif, but I will gladly change the font to whatever you may prefer.

**Comment by pdimens** [comment]
Here is another draft, using blue/yellow like your mockup above, serif text, julia styling
![image](https://user-images.githubusercontent.com/19176506/227266840-4436cfa9-18f1-4a18-a564-29e4e1c1693a.png)

**Comment by pdimens** [comment]
@lazarusA any consensus on this?

**Comment by lazarusA** [comment]
waiting for @meggart feedback here, let's do it for now until a new refactor is in place. 
I will say left. Or maybe right with the cube from the left 😄.

**Comment by gdkrmr** [comment]
My 2 cents:
- Why are the slices not regular?
- The gaps between cubes are too small, this must look good when reduced in size
- Why not use a more modern font without serifs?

**Comment by pdimens** [comment]
@gdkrmr 
1. What do you mean not regular? The viewing perspective is what makes the bricks appear to be different sizes
2. Gaps can be increased, that's trivial
3. Please suggest a font. There are thousands and it will not be a good use of time to upload dozens of screenshots for individual approval.

**Comment by gdkrmr** [comment]
> * What do you mean not regular? The viewing perspective is what makes the bricks appear to be different sizes

With not regular I mean that the chunks are of different sizes, you have some that are (3, 1, 1) in size and others that are (1, 3, 1) in size.

> 
> * Gaps can be increased, that's trivial
> 
> * Please suggest a font. There are thousands and it will not be a good use of time to upload dozens of screenshots for individual approval.


Something that looks more modern. The name is also quite long, so I would go with something condensed and drop the .jl at the end. I prepared some samples below

From top to bottom:

- Fira Sans
- Droid Sans
- Fira Sans Condensed
- Nimbus Sans
- Nimbus Sans Narrow
- Bitstream Vera Sans
- DejaVu Sans
- TeX Gyre Heros Cn

My favorite is Fira Sans Condensed.

![bitmap](https://user-images.githubusercontent.com/12512930/229063487-eb4a1421-099b-426b-992c-39980bd20ebf.png)

**Comment by lazarusA** [comment]
I don't like the idea about dropping the `.jl` part from the name. That's like the signature of any Julia package. Plus is easier to google it, the results are more consistent.

**Comment by gdkrmr** [comment]
> I don't like the idea about dropping the `.jl` part from the name. That's like the signature of any Julia package. Plus is easier to google it, the results are more consistent.

You are probably right about findability. I think package name is quite long already, adding .jl is probably better.

> I really like the design of the last logo, however, I agree with Guido that the chunks should have the same shape in each of the layers to reflect a bit more on what the internal chunking of a real dataset would look like

Agreed, the logo is cool, just needs some adjustment.

**Comment by pdimens** [comment]
Here are two variants with equal chunks.

![image](https://user-images.githubusercontent.com/19176506/229894863-8446bf0c-6d61-4494-ada4-931ce7d3a7fe.png)

**Comment by pdimens** [comment]
@gdkrmr @lazarusA 
What are you opinions of the 4 latest drafts?

**Comment by lazarusA** [comment]
I would go for a PR with number 2, latest post with YAXArrays.jl (first font option from @gdkrmr ).

**Comment by gdkrmr** [comment]
Sorry for not replying earlier I really like the new logo. Thanks for taking the time to do this!. I think it looks very cool!
