### ISSUE TITLE
open_mfdataset function not exported?

### ISSUE THREAD

**Issue by Balinus** [JuliaDataCubes/YAXArrays.jl#247]
Hello!

I have a collection of yearly files from 1981 top 2020 for a single variable. Is there a way to open those files and build a Cube from it? I saw a function called `open_mfdataset` in the source code, but it does now seem to be exported. By copy-pasting the code found in https://github.com/JuliaDataCubes/YAXArrays.jl/blob/43640165301bdcf49fa3cc763414715174585fbb/src/DatasetAPI/Datasets.jl I was able to load a multifile dataset correctly. 

Is it still experimental?

Thanks!

**Comment by lazarusA** [comment]
you should be able to do 

```Julia
t2m = YAXArrays.Datasets.open_mfdataset(inpath * "t2m/*.nc").t2m[time=2001:2021]
```
or the full time period

```Julia
t2m = YAXArrays.Datasets.open_mfdataset(inpath * "t2m/*.nc")
```

but be careful, is never a good idea to use `*.nc` to ready all files unless you are sure about them.

**Comment by Balinus** [comment]
Ah, thanks! I was trying to use `YAXArrays.open_mfdataset` 😄 

It does work!
