### ISSUE TITLE
The `YAXArray` construction with named Axes example fails.

### ISSUE THREAD

**Issue by Qfl3x** [JuliaDataCubes/YAXArrays.jl#294]
[This example](https://juliadatacubes.github.io/YAXArrays.jl/dev/examples/generated/UserGuide/creating/#axis-definitions) in the wiki fails with error:

````
ERROR: MethodError: no method matching axsym(::Dim{:time, StepRange{Date, Day}})

Closest candidates are:
  axsym(::CubeAxis{<:Any, S}) where S
   @ YAXArrays ~/.julia/packages/YAXArrays/au5n4/src/Cubes/Axes.jl:164
````
Tried to make other YAXArrays with `Dim` and it always fails.

**Comment by felixcremer** [comment]
Are you on version 0.5? From the method error it seems as if there is still a CubeAxis type. This should not be defined anymore.

**Comment by Qfl3x** [comment]
It's weird. I've rerun it and it works, should've been the same environment.
