### ISSUE TITLE
don't do Ti, better to have Dim{:time}

### ISSUE THREAD

**Issue by lazarusA** [JuliaDataCubes/YAXArrays.jl#301]
The current behaviour is to do `Ti` for the time axis, even if I set initially my dimension to `Dim{:time}` and I can see that printed, after saving and reading back again I see `Ti` which is really not good.  Could we just have  `Dim{:time}`, always? and not rely on `Ti`.

**Comment by gdkrmr** [comment]
I agree here! Having "special" dimensions is antithetical to the data cube philosophy!

**Comment by Balinus** [comment]
Perhaps it is related to #330 ?

The whole `Ti` is cumbersome imho since it seems to override that is inside the files natively.
