### ISSUE TITLE
Cannot save cube with Coord as dim

### ISSUE THREAD

**Issue by TabeaW** [JuliaDataCubes/YAXArrays.jl#305]
Is it right that it is not possible to save a cube with a dimension of Type Coord, yet?
Either ` MethodError: no method matching defaultfillval(::Type{Tuple{ Float64, Float64}})` or when overwriting `YAXArrayBase.defaultfillval(T::Type{Tuple{,Float64,Float64}})=(1e32,1e32)` `DirectoryStore("cube.zarr")  is not empty` is my problem.

**Comment by lazarusA** [comment]
please free to re-open with a MWE. As it stands, I don't get what this Type Coord is.
