### ISSUE TITLE
Export DimensionalData selectors?

### ISSUE THREAD

**Issue by dpabon** [JuliaDataCubes/YAXArrays.jl#315]
Not sure if it's a good idea to export the selectors from DimensionalData.jl package:

Selectors are wrappers that indicate that passed values are not the array indices, but values to be selected from the dimension index, such as DateTime objects for a Ti dimension.

Selectors provided in DimensionalData are:
[At](https://docs.juliahub.com/DimensionalData/Unppe/0.16.0/api/#DimensionalData.At)
[Between](https://docs.juliahub.com/DimensionalData/Unppe/0.16.0/api/#DimensionalData.Between)
[Near](https://docs.juliahub.com/DimensionalData/Unppe/0.16.0/api/#DimensionalData.Near)
[Where](https://docs.juliahub.com/DimensionalData/Unppe/0.16.0/api/#DimensionalData.Where)
[Contains](https://docs.juliahub.com/DimensionalData/Unppe/0.16.0/api/#DimensionalData.Contains)

Otherwise, it is necessary to load YAXArrays and DimensionalData package each time.

```julia
using YAXArrays, DimensionalData
```

**Comment by lazarusA** [comment]
these re-exported now, but DD has a lot more functions. So, usually loaded is a good idea.
