### ISSUE TITLE
Make it possible to create a skeleton without allocating memory.

### ISSUE THREAD

**Issue by Qfl3x** [JuliaDataCubes/YAXArrays.jl#343]
The current guide on creating a skeleton:
````julia
using YAXArrays, Zarr
a = YAXArray(zeros(Union{Missing, Int32},10,20))
f = tempname();
r = savecube(a,f,driver=:zarr,skeleton=true);
all(ismissing,r[:,:])
````
allocates memory during the `zeros` call, which is counter-intuitive to the idea of a skeleton, as well as very memory intensive.

**Comment by lazarusA** [comment]
please consider doing a PR using FillArrays, see here: https://github.com/JuliaDataCubes/YAXArrays.jl/issues/248 (duplicated of this)

**Comment by lazarusA** [comment]
close by https://github.com/JuliaDataCubes/YAXArrays.jl/pull/344
