### ISSUE TITLE
Improve printing of YAXArrays.Dataset

### ISSUE THREAD

**Issue by felixcremer** [JuliaDataCubes/YAXArrays.jl#352]
We could improve the printing of the Dataset by trying to sort the cubes by shared axes. Currently, if there is one cube without any axes all other cubes will have their axes printed seperately. 
This is an example of such a cube:

```julia
url = "http://esgf1.dkrz.de/thredds/fileServer/cosmo-rea/reanalysis/EUR-6km/DWD/ECMWF-ERAINT/REA6/r1i1p1f1/COSMO/v1/mon/atmos/tas/v20230314/tas_EUR-6km_ECMWF-ERAINT_REA6_r1i1p1f1_COSMO_v1_mon_200401-200412.nc"
filename = split(url, "/")[end]
mkpath("data/")
path = download(url, "data/$filename")
ds = open_dataset(path)
```

Here the `height` cube is a zero dimensional cube and throws off all other printing.

**Comment by lazarusA** [comment]
this should be fix by https://github.com/JuliaDataCubes/YAXArrays.jl/pull/435
