### ISSUE TITLE
Converting calendar of an Array or Dataset?

### ISSUE THREAD

**Issue by Balinus** [JuliaDataCubes/YAXArrays.jl#357]
Hello!

I'd like to convert a given dataset from a "regular" calendar to a DateTimeNoLeap calendar (and dropping all 29th Feb data along the way). 

Is there a way to do it? I tried to find a solution, but they all involved loading the data in-memory, checking datetime vector, dropping the indexes associated with Feb 29th and then rebuilding a Dataset. I'd like it to be lazy because most of the datasets are in the 20GB range. 

Thanks for any pointer!

**Comment by felixcremer** [comment]
You can use the `Not` selector with a vector of the leap days either with an inner At or Near selector. 
```
julia> winter = r1[Ti=Not(At([DateTime(1995, 4,16),DateTime(1995,10,16,12)]))]
julia> typeof(winter.data)
DiskArrays.SubDiskArray{Union{Missing, Float32}, 3}
``` 
You have to be careful to match the Date or DateTime type with the type of your time axis. 
This subsetting will give you a lazy SubDiskArray which handles the subsetting via the metadata without having to load the data to memory.

**Comment by Balinus** [comment]
Thanks! I was about to write a potentiel solution that seems to work no matter the type of Date/DateTime

```julia
ref_tasmax[Time=Dates.monthday.(lookup(ref_tasmax, :Ti)) .!= [(2,29)]]
```

Seems to be lazy and worked with dataset with regular Datetime and DateTimeNoLeap calendars. Then, I will need to replace the axis with a new type (e.g. from `DateTime` to `DateTimeNoLeap`).

Does this code make sense?

**Comment by felixcremer** [comment]
That looks good. 
You could replace your subsetting with a Where selector like this:

```julia
ds[Ti=Where(x-> Dates.monthday(x) != (2,29))]
```
but I am not sure whether there is  much of a difference. 
I think there might also a way to only rebuild the time axis and leave the other axes as is. 
But this is some DimensionalData function that I would also need to lookup.
You might want to not rebuild the lon and lat axis like that but use `dims(ds_subset, :lon) instead this way you get the whole axis with all of the correct reversings and so on.


Could you add this example to the docs. That would be really nice.

**Comment by Balinus** [comment]
> That looks good. You could replace your subsetting with a Where selector like this:
> 
> ```julia
> ds[Ti=Where(x-> Dates.monthday(x) != (2,29))]
> ```
> 
> but I am not sure whether there is much of a difference. I think there might also a way to only rebuild the time axis and leave the other axes as is. But this is some DimensionalData function that I would also need to lookup. You might want to not rebuild the lon and lat axis like that but use `dims(ds_subset, :lon) instead this way you get the whole axis with all of the correct reversings and so on.
> 
> Could you add this example to the docs. That would be really nice.

Thanks! Yes, I will include it. Somewhere specific in the documentation?

**Comment by Balinus** [comment]
Also, I'm unsure how the "Time" dimension (`Ti`?) is handled. It seems to be a "special" dimensions and when I rebuild the time dimension now behaves as a regular dimension. Sometimes, the time dimension is accessible with `Ti`, sometimes not.
