### ISSUE TITLE
Opening a set of NetCDF fails

### ISSUE THREAD

**Issue by Sonicious** [JuliaDataCubes/YAXArrays.jl#365]
Opening a set of NetCDF results in error through multiple ways:

```julia
using YAXArrays, NetCDF

filelist = readdir("Path/to/NetCDF/directory", join = true)
Cube = YAXArrays.Datasets.open_mfdataset(filelist) # ERROR: KeyError: key :Ti not found
```

```julia
using YAXArrays, NetCDF
filelist = readdir("Path/to/NetCDF/directory", join = true)
cubes = Cube.(filelist)
cat(cubes...,dims=Ti) # ERROR: TypeError: in keyword argument dims, expected Int64, got a value of type Tuple{Int64}
```

Is there a way to use a bunch of netcdf and open them? Is there an alternative way to convert these to a zarr archive?

**Comment by felixcremer** [comment]
On what version of DiskArrays are you? With DiskArrays master the last version should work.

**Comment by Sonicious** [comment]
According to Manifest.toml I use `version = "0.3.22"` which is the latest release coupled with YAXArrays 0.5.3

**Comment by felixcremer** [comment]
Yes, we need to tag a new DiskArrays release.

**Comment by felixcremer** [comment]
With DiskArrays 0.3.23 `cat` should work.

**Comment by Sonicious** [comment]
In case of `cat(cubes...,dims=Ti)` I now get `ERROR: KeyError: key :Ti not found`

**Comment by lazarusA** [comment]
close by #470, #481
