### ISSUE TITLE
show of list of YAXArray reads data

### ISSUE THREAD

**Issue by felixcremer** [JuliaDataCubes/YAXArrays.jl#366]
When we show a list of YAXArrays the data is shown and not the metadata overview. This can make showing quite slow because we pay the reading overhead to get to the data. I am wondering whether this is hitting some fallback in DimensionalData.jl.

@rafaqz

**Comment by rafaqz** [comment]
Yeah I guess we need `show(io, ::DimArray)` method but I never know what youre supposed to do there

**Comment by felixcremer** [comment]
This is basically the same as https://github.com/rafaqz/DimensionalData.jl/issues/498. I think we could solve this on the AbstractDimArray level.

**Comment by lazarusA** [comment]
not an issue anymore.
