### ISSUE TITLE
Geo Ecosystem: Feedback

### ISSUE THREAD

**Issue by lazarusA** [JuliaDataCubes/YAXArrays.jl#367]
Hey! 

I'm in the process of uploading new docs for yax. I would like to put together  a list of packages for the Julia Geo Ecosystem, maybe closely related to YAX.... such as 

`NetCDF`, `Zarr`, `DiskArrays`.... what else am I missing... surely a lot. 

thanks for your feedback.. @felixcremer @meggart @rafaqz.

**Comment by rafaqz** [comment]
Just Makie too cos you can plot direct with DD....
