### ISSUE TITLE
Write docs based on the four pillars of documentatoin

### ISSUE THREAD

**Issue by felixcremer** [JuliaDataCubes/YAXArrays.jl#38]
This is a nice explanation of the four functions of documentation:
https://documentation.divio.com/introduction/
The four parts are:
Tutorials
How-to guides
Reference
Explanation

From our discussion earlier, the next steps for the documentation are:
- [ ] Write a tutorial @meggart 
- [ ] Write a how to use Tiff files (or arbitrary files from GDAL) in YAXArrays @felixcremer 
- [x] Exposing the docstrings as a reference guide @felixcremer See #41 
- [ ] Write a performance tips section to explain the influence of chunking and parallel computation on the performance. @meggart 

I'd like to use this issue to track the development of the documentation.

**Comment by felixcremer** [comment]
Check for public tiff files to write the gdal tutorial.

**Comment by lazarusA** [comment]
new docs, cover most of these things if not all.
