### ISSUE TITLE
deploying latest release

### ISSUE THREAD

**Issue by lazarusA** [JuliaDataCubes/YAXArrays.jl#385]
currently, we don't see the new release version in the gh-pages branch. Any hints? @asinghvi17

**Comment by asinghvi17** [comment]
The documenter build did not run on the tag - this is a Github Actions issue.  Do you have a `DOCUMENTER_KEY` set up in the repo @felixcremer

**Comment by lazarusA** [comment]
@felixcremer I don't have security clearance to check that 😄 , could your please double check that?

**Comment by lazarusA** [comment]
close by #407
