### ISSUE TITLE
404 on stable documentation URL

### ISSUE THREAD

**Issue by Balinus** [JuliaDataCubes/YAXArrays.jl#425]
When clicking on the link for the documentation, the URL goes to "stable" (https://juliadatacubes.github.io/YAXArrays.jl/stable/), which leads to a 404 page. 

![image](https://github.com/user-attachments/assets/97f1d27f-da5f-48af-80d3-68e688180c72)

**Comment by asinghvi17** [comment]
Oh no!  @lazarusA even YAX is infected by this thing.

There's a solution you can put in the `gh-pages` branch [here](https://github.com/JuliaGeo/GeometryOps.jl/blob/gh-pages/.github/workflows/DeployDocs.yml) and you then set the Github Pages deployment method to "Actions".  But we need a long term fix that will probably only come from DocumenterVitepress.
