### ISSUE TITLE
Loading data in memory vs out of memory: indication in show + conversion + option when opening dataset

### ISSUE THREAD

**Issue by briochemc** [JuliaDataCubes/YAXArrays.jl#447]
I'm not sure if this had not been asked before or if I should ask elsewhere, but since I was using YAXArrays I thought I should ask here. Maybe this is already doable and I just don't know how. Anyway, here is a triple feature request:

- [x] It would be nice if the (very nice) `show` method also showed whether the parent data has been loaded in memory or not. Maybe a "`(loaded lazily)`/`(loaded in memory)`" or similar wording?

- [x] It would also be nice if the docs showed how to load the data in memory from a lazily loaded variable `var`. My understanding is that I should use `modify(Array, var)`.

- [x] It may be worth having an option to load data in memory when "opening" a dataset, e.g., maybe with the syntax `ds = open_dataset(...; in_memory = true)`, it would force the data to be loaded in memory? (With default `in_memory = false` I guess?)

**Comment by lazarusA** [comment]
hey,
1. loaded lazily)/(loaded in memory). I guess we could do that. 
2. see [readcubedata](https://juliadatacubes.github.io/YAXArrays.jl/dev/api.html#YAXArrays.Cubes.readcubedata-Tuple{Any}). Better docs are needed for that one.
3. maybe just combine with 2?

**Comment by rafaqz** [comment]
Rasters uses `Base.read` and DD forwards it on. Maybe YAX could add that too?

**Comment by lazarusA** [comment]
Yeah, don't know. `open` and `save` -> `open_dataset`, `savecube` and `save_dataset`, need some unification work.

**Comment by briochemc** [comment]
Another one would be to be able to read en entire `YAXArray Dataset` in memory. Is it possible to do so at this stage or does one need to `readdatacube` for all vars separately?

**Comment by felixcremer** [comment]
I implemented readcubedata for Datasets in #453 and I also added a hint to the data loading in the show method. 
This should solve this issue.

**Comment by lazarusA** [comment]
close by https://github.com/JuliaDataCubes/YAXArrays.jl/pull/453 , https://github.com/JuliaDataCubes/YAXArrays.jl/pull/457
