### ISSUE TITLE
All axis names

### ISSUE THREAD

**Issue by lazarusA** [JuliaDataCubes/YAXArrays.jl#46]
Is there a simple way to obtain all the axis names within a dataset?, like in a dict. Something like:

```
> getAxisNames(cube)
name1
name2
name3
      -name3.1
      -name3.2
```
the case of name3 will be if we have nested variables.

**Comment by meggart** [comment]
You can obtain the axes of a cube through `cube.axes`. If you are only interested in the names, there is the(currently nonexported) function `YAXArrays.Cubes.Axes.axname`. So to answer your question to get all axis names of a cube, you can do:

````julia
YAXArrays.Cubes.Axes.axname.(cube)
````

maybe we should think about exporting this.

**Comment by meggart** [comment]
The best option is probably `YAXArrayBase.dimnames`

**Comment by lazarusA** [comment]
I will tried this one 😃 . Just for context: I was planning on using this in order to have a drop-down menu for plotting the different variables on demand.
