### ISSUE TITLE
Automatic parsing of dimension names leads to duplicated 'Ti' dimensions

### ISSUE THREAD

**Issue by jamesafranke** [JuliaDataCubes/YAXArrays.jl#468]
Hi! Love the package!

```
using YAXArrays, Zarr 
ds = open_dataset( zopen( "gs://weatherbench2/datasets/keisler/2020-360x181.zarr") )
```

leads to:
<img width="622" alt="Screen Shot 2024-11-07 at 2 20 56 PM" src="https://github.com/user-attachments/assets/ccb95a95-332f-4b61-b399-9e59cfdff454">

The original dataset has a `time` and a `prediction_timedelta` (forecast horizon). I cannot find where this is getting automatically parsed into `Ti`. Maybe it is within `DimensionalData.jl` somewhere. Any way to override this behavior? 

<img width="702" alt="Screen Shot 2024-11-07 at 2 23 06 PM" src="https://github.com/user-attachments/assets/d96e8b36-154f-4cd9-bc6e-0dc5b6b4dce4">

**Comment by jamesafranke** [comment]
I was able to rename one of the axes for a single cube:

`temp = renameaxis!(ds.temperature, :Ti=>:Ti2)`

<img width="675" alt="Screen Shot 2024-11-07 at 2 48 22 PM" src="https://github.com/user-attachments/assets/143ae80f-a109-46a6-8d52-a1a68d6a13dc">

Since two time axes is somewhat rare...probably fine to just do it this way. 😄

**Comment by Balinus** [comment]
I think this is still a problem that the parsing gives the same name to 2 dimensions. I still believe that the renaming from "time" (standard dimension name in 99% of climate and weather datasets) to "Ti" is not a good practice for interconnexion with other packages that often hardcode "time" in their packages (sometimes using PyCall to use some Python libraries).

**Comment by lazarusA** [comment]
see https://github.com/rafaqz/DimensionalData.jl/issues/499. 

as a side note I  usually try to do `dim{:time}` in my workflows 😄 .  Maybe we should do this in the yax side and don't fall back to `Ti`. ...

**Comment by jamesafranke** [comment]
@lazarusA thanks!

**Comment by Balinus** [comment]
Another example of this behaviour leading to sometimes strange results (or more spcifically, leading to a bad interpretation of what the data is).

Coordinates saved to disk:
```python
Coordinates:
  * lat            (lat) float32 1kB 10.12 10.38 10.62 ... 73.88 74.12 74.38
  * lead           (lead) int64 32B 1 4 7 10
  * lon            (lon) float32 2kB -169.9 -169.6 -169.4 ... -50.38 -50.12
  * quantiles      (quantiles) float64 152B 0.05 0.1 0.15 0.2 ... 0.85 0.9 0.95
  * forecast_date  (forecast_date) datetime64[ns] 4kB 1981-01-15 ... 2024-03-15
```

Coordinates read by YAXArrays:
```julia
(↓ quantiles Sampled{Float64} 0.05:0.05:0.95 ForwardOrdered Regular Points,
  → lon       Sampled{Float32} -169.875f0:0.25f0:-50.125f0 ForwardOrdered Regular Points,
  ↗ lat       Sampled{Float32} 10.125f0:0.25f0:74.375f0 ForwardOrdered Regular Points,
  ⬔ lead      Sampled{Int64} 1:3:10 ForwardOrdered Regular Points,
  ◩ Ti        Sampled{DateTime} [1981-01-15T00:00:00, …, 2024-03-15T00:00:00] ForwardOrdered Irregular Points)
```

Hence, `forecast_date` is inferred as the time dimension, which is OK as a first approximation. However, using `Ti` remove the meaning of a `forecast_date` (which could be not correlated to the meaning of a specific date).

**Comment by lazarusA** [comment]
ok, definitely a bug. Any pointers @felixcremer ? we need to update the logic for this.

**Comment by meggart** [comment]
The logic is basically in this line: https://github.com/JuliaDataCubes/YAXArrays.jl/blob/cac79bfc0a659c527dea616b24b98e21e2ddf0c2/src/DatasetAPI/Datasets.jl#L288
This means, whenever something is encoded as a CF convention time dimension, it will get the label `Ti`. 

We could change this line to

````julia
DD.rebuild(DD.name2dim(axname),tsteps[offs+1:end])
````

 and then dimension names would remain untouched. I know in the beginning of our transition to DD we were doing this but then somehow ran into problems elsewhere but I can not remember what it was, maybe @felixcremer can remember. In the light of the issues brought up here I completely agree we should change something in the logic of when and if at all to parse things as `Ti`, `X` and `Y`.

**Comment by meggart** [comment]
Ideally I think the user should be able to decide if they want the re-labelling of the dimensions so that the arrays work better with plot recipes etc or not. Maybe this could even happen in an extra step. One suggestion would be that something like this would be possible:

````julia
ds = open_dataset(path) # returns lon, lat, time etc...
ds_labeled = fixspacetimedims(ds)
````

where the (to be written) `fixspacetimedims` function searches for occurences of `lon` or `lat` and `time` in all their spelling variants and replaces the dimension types (maybe even after user-specified rules) while making sure we only end up with a single `X`, `Y` and `Ti`.

**Comment by Balinus** [comment]
I think having the option to relabel is a good suggestion. It would be nice to not lose the plot recipes and still keep the original dimensions names. Perhaps, within the `open_dataset` function to have a keyword arg, like `keep_original_name` logic? 

Alternatively, is it possible to specify, at the plot recipe level, the X, Y, Ti dimensions to use?

Something like :

```julia
Makie.contourf(ds, X=:longitude, Y:latitude)
```
Not sure what is best or easiest.

**Comment by felixcremer** [comment]
I am wondering whether we could keep the dim name but make it a subtype of Ti if we detect it as a CF time dimension
